################ Portuguese language ##################
[pt-BR]
languageName = "Português"
languageCode = "pt-br"
contentDir = "content/portuguese"
weight = 1

################ English language ##################
[en]
languageName = "Inglês"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
