############# Navegação em Português ##############

# menu principal
[[main]]
name = "Início"
url = "/"
weight = 1

[[main]]
name = "Sobre"
url = "/about"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 3

[[main]]
name = "Contato"
url = "/contact"
weight = 4

# menu do rodapé
[[footer]]
name = "Sobre"
url = "/about"
weight = 1

[[footer]]
name = "Blog"
url = "/blog"
weight = 2

[[footer]]
name = "Política de Privacidade"
url = "/privacy-policy"
weight = 3
